development:
  adapter: postgresql
  username: jsuchy
  password:
  database: cookbook_develpoment
  encoding: utf8
  template: template0

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

cucumber:
  <<: *test

