development:
  adapter: mysql2
  database: cookbook_development
  username: root
  password:
  socket: /tmp/mysql.sock

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

cucumber:
  <<: *test

